// SPDX-License-Identifier: GPL-3.0-or-later WITH GPL-3.0-linking-exception
// Copyright (C) 2026 The Regents of the University of Michigan
// This file is part of COMPAS, free software under the GNU General Public License,
// version 3 or later, with an additional permission under section 7. It comes with
// ABSOLUTELY NO WARRANTY. See COPYRIGHT and LICENSE for details.

#ifndef Operators_PhaseField_H_
#define Operators_PhaseField_H_

#include<FDM_ChemicalPotential_VanDerWaals_D.H>
#include<FDM_ChemicalPotential_VanDerWaals_K.H>

#include<FDM_ChemicalPotential_Adv_D.H>
#include<FDM_ChemicalPotential_Adv_K.H>
#include<FDM_ChemicalPotential_Adv_NormalFace_D.H>
#include<FDM_ChemicalPotential_Adv_NormalFace_K.H>

#include<FDM_PhaseFieldMechanism_ACVanDerWaals_D.H>
#include<FDM_PhaseFieldMechanism_ACVanDerWaals_K.H>

#include<FDM_PhaseFieldMechanism_ACAdv_D.H>
#include<FDM_PhaseFieldMechanism_ACAdv_K.H>
#include<FDM_PhaseFieldMechanism_ACAdv_NormalFace_D.H>
#include<FDM_PhaseFieldMechanism_ACAdv_NormalFace_K.H>

#include<FDM_PhaseFieldFlux_CDI_D.H>
#include<FDM_PhaseFieldFlux_CDI_K.H>
#include<FDM_PhaseFieldFlux_CDI_CompressionInterpolation_D.H>
#include<FDM_PhaseFieldFlux_CDI_CompressionInterpolation_K.H>
#include<FDM_PhaseFieldFlux_CDI_NormalFace_D.H>
#include<FDM_PhaseFieldFlux_CDI_NormalFace_K.H>

#include<FDM_PhaseFieldFlux_ACDI_D.H>
#include<FDM_PhaseFieldFlux_ACDI_K.H>
#include<FDM_PhaseFieldFlux_ACDI_NormalFace_D.H>
#include<FDM_PhaseFieldFlux_ACDI_NormalFace_K.H>

#endif