// SPDX-License-Identifier: GPL-3.0-or-later WITH GPL-3.0-linking-exception
// Copyright (C) 2026 The Regents of the University of Michigan
// This file is part of COMPAS, free software under the GNU General Public License,
// version 3 or later, with an additional permission under section 7. It comes with
// ABSOLUTELY NO WARRANTY. See COPYRIGHT and LICENSE for details.

#ifndef Physics_Compressible6Eq_PhaseField_H_
#define Physics_Compressible6Eq_PhaseField_H_

#include<ConservativePhase2FluxPhasePhaseField_Compressible6Eq_PhaseField.H>
#include<FluxPhasePhaseField_UD_Compressible6Eq_PhaseField.H>
#include<FluxPhasePhaseField_HLL_Compressible6Eq_PhaseField.H>

#include<FluxPhaseField_Mixture_Compressible6Eq_PhaseField.H>
#include<FluxPhasePhaseField2FluxPhaseField_Mixture_Compressible6Eq_PhaseField.H>
#include<FluxPhaseField_Compressible6Eq_PhaseField.H>


#endif