// SPDX-License-Identifier: GPL-3.0-or-later WITH GPL-3.0-linking-exception
// Copyright (C) 2026 The Regents of the University of Michigan
// This file is part of COMPAS, free software under the GNU General Public License,
// version 3 or later, with an additional permission under section 7. It comes with
// ABSOLUTELY NO WARRANTY. See COPYRIGHT and LICENSE for details.

#ifndef Physics_Compressible_NPhase_H_
#define Physics_Compressible_NPhase_H_

#include<Component2VectorPhase_Compressible_NPhase.H>
#include<VectorPhase2Component_Compressible_NPhase.H>
#include<ConservativePhase2State_Compressible_NPhase.H>
#include<State2ConservativePhase_Compressible_NPhase.H>



#endif