// SPDX-License-Identifier: GPL-3.0-or-later WITH GPL-3.0-linking-exception
// Copyright (C) 2026 The Regents of the University of Michigan
// This file is part of COMPAS, free software under the GNU General Public License,
// version 3 or later, with an additional permission under section 7. It comes with
// ABSOLUTELY NO WARRANTY. See COPYRIGHT and LICENSE for details.

#ifndef Physics_Compressible_NPhase_PhaseField_H_
#define Physics_Compressible_NPhase_PhaseField_H_

#include<VelocityPhaseField_Base_Compressible_NPhase_PhaseField.H>
#include<VelocityPhaseField_Efficient_Compressible_NPhase_PhaseField.H>
#include<ConservativePhase2FluxPhasePhaseField_Compressible_NPhase_PhaseField.H>
#include<FluxPhasePhaseField_UD_Base_Compressible_NPhase_PhaseField.H>
#include<FluxPhasePhaseField_UD_Efficient_Compressible_NPhase_PhaseField.H>
#include<FluxPhasePhaseField_HLL_Compressible_NPhase_PhaseField.H>

#endif