// SPDX-License-Identifier: GPL-3.0-or-later WITH GPL-3.0-linking-exception
// Copyright (C) 2026 The Regents of the University of Michigan
// This file is part of COMPAS, free software under the GNU General Public License,
// version 3 or later, with an additional permission under section 7. It comes with
// ABSOLUTELY NO WARRANTY. See COPYRIGHT and LICENSE for details.

#ifndef Physics_Derived_Classes_H_
#define Physics_Derived_Classes_H_

#include <Class_Compressible_PhaseField.H>
#include <Class_Compressible5Eq_PhaseField.H>
#include <Class_Compressible5Eq_NPhase_PhaseField.H>
#include <Class_Compressible6Eq_PhaseField.H>
#include <Class_Compressible6Eq_IE_NPhase_PhaseField.H>

#endif 